name: Demonstrating job output

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      greeting: ${{ steps.hello.outputs.greeting }}
    steps:
      - name: Generate Greeting
        id: hello
        run: echo "::set-output name=greeting::Hello, World!"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Greeting from Job 1
        run: echo "The greeting from job1 is ${{ needs.job1.outputs.greeting }}"
